### ISSUE TITLE
Hur ser jobbmöjligheterna i Sverige ut inom IT-säkerhet? Finns det något man bör tänka på som student med inte SÅ mycket kvar av studierna?

### ISSUE THREAD

**Issue by JohanRM** [mjidhage/sakerhetspodcasten#11]
Från ask.fm.

**Comment by mjidhage** [comment]
Undras vad som händer om jag svarar på detta?
/M

**Comment by JohanRM** [comment]
Haha, try it ;)

2014-03-17 13:16 GMT+01:00 mjidhage notifications@github.com:

> Undras vad som händer om jag svarar på detta?
> /M
>

**Comment by mjidhage** [comment]
Ah, ok. Det coola var alltså att jag svarade på ett notifieringsmail jag fick. När jag gjorde det så gick svaret direkt in i kommentars-tråden. Det var coolt. _Gillar_

**Comment by JohanRM** [comment]
Mitt med. Undrar om man kan fucka med det på något sätt...

Den 17 mars 2014 13:29 skrev mjidhage notifications@github.com:

**Comment by mjidhage** [comment]
Det kan man säkert
