### ISSUE TITLE
FRÅGA? Fly by wire

### ISSUE THREAD

**Issue by Jesperofsweden** [mjidhage/sakerhetspodcasten#23]
Ang. fly-by-wire:
http://www.techspot.com/news/52211-hacker-demonstrates-how-to-hijack-an-airplane-using-an-android-app.html

Med vänliga hälsningar
Andreas Bergström

2014-03-17 15:43 GMT+07:00 Andreas Bergström andreas.bergstrom@gmail.com:
Förresten, hela konceptet fly-by-wire som sitter i bl.a. Boeing 777 verkar ju väldigt intressant att pentesta.

http://en.wikipedia.org/wiki/Fly-by-wire

Med vänliga hälsningar
Andreas Bergström

2014-03-17 15:26 GMT+07:00 Andreas Bergström andreas.bergstrom@gmail.com:

http://edition.cnn.com/2014/03/16/opinion/palmer-malaysia-flight-370/index.html?hpt=hp_c3

Verkar finns mycket i ACARS som skulle vara värt att titta på säkerheten i.

Statements that the Aircraft Communications Addressing and Reporting System was intentionally disabled, for example, leave out the fact that the ACARS is required to send the satellite contact requests (so-called "handshakes") that, according to news reports, were reported to have occurred for hours after the flight's disappearance.

For example, one part of this communications system is used for messages between the airplane and air traffic control (clearances, position reports, etc). Another is used to communicate, essentially with text messages, between the airplane and the airline. Messages can also be sent automatically for maintenance functions such as reporting faults and sending routine engine data. The range of functions that would have been available for someone to disable is not yet clear.

Med vänliga hälsningar
Andreas Bergström

**Comment by blaufish** [comment]
flyttad till backlogg och stängd
