### ISSUE TITLE
Windows 8 är 21 gånger säkrare än windows XP 

### ISSUE THREAD

**Issue by Jesperofsweden** [mjidhage/sakerhetspodcasten#24]
Hej får tacka för en super podcast! Enda tråkiga med den skulle jag säga är att den kommer ut så ofta då jag skulle vela lysna på den varje dag påväg till skolan 😉

Hej jag har på senast läst endel om hur det påstås att Windows 8 ska vara 21 gånger än Windows xp och 6 gånger säkrare än Windows 7. Jag undrar vad ni tänker om det och vad det har för verklighetsförankring för jag tror inte att man kan sätta ett sådant absolut värde. Samt vad tycker att Windows 8 är säkrare än de andra versionerna?

Jag skulle även uppskatta om ni kunde göra ett avsnitt mer riktade mot “ikte så kunnande” personer där ni går igenom hash(ning), salt osv vad det är och hur det funkar. Samt om ni skulle vela ha med en icke insat person i säkerhet men någon gång som är intresead och någorlunda teknikunig så finns jag här! :D

kanske ska tilläga att  jag är studerande vid SU (Stockholms universitet) pluggande Data och systemvetenskap.

Med Vänliga Hälsningar
Linus Ahlin-Hamberg

**Comment by blaufish** [comment]
Besvarad i nästa podcast
