### ISSUE TITLE
Shownotes StateSponsored-AngryBirds-Malware

### ISSUE THREAD

**Issue by mjidhage** [mjidhage/sakerhetspodcasten#27]

**Comment by blaufish** [comment]
Operation Olympic Games

Det påstådda CIA/Israel op som 2006-2010 skall ha motiverat Stuxnet attacken mot Iran http://en.wikipedia.org/wiki/Operation_Olympic_Games
Stuxnet 0.5 (2005-2009)

Stuxnet 0.5 The Missing Link http://www.symantec.com/connect/blogs/stuxnet-05-missing-link
Stuxnet  1.x (2009 – 2010)

Stuxnet http://en.wikipedia.org/wiki/Stuxnet
Duqu

Duqu http://en.wikipedia.org/wiki/Duqu
Duqu http://www.crysys.hu/publications/files/bencsathPBF11duqu.pdf
Flame (2007 – 2012)

Flame http://en.wikipedia.org/wiki/Flame_(malware)
Skywiper http://www.crysys.hu/skywiper/skywiper.pdf
Den civila MD5-attacken från 2008 Rouge CA: MD5 considered harmfull today http://www.win.tue.nl/hashclash/rogue-ca/
Gauss (2011-2012)

Gauss http://www.securelist.com/en/blog/208193767/Gauss_Nation_state_cyber_surveillance_meets_banking_Trojan
Encrypted payload http://www.securelist.com/en/blog/208193781/The_Mystery_of_the_Encrypted_Gauss_Payload
oclGaussCrack http://hashcat.net/oclGaussCrack/
Rykterna om att Kapersky<->FSB (KGB) länk

Wired http://www.wired.com/2012/07/ff_kaspersky/all/
Superrubriken från amerikansk slasknyheter:

Powerful ‘Flame’ cyberweapon tied to popular Angry Birds game http://www.foxnews.com/tech/2012/05/30/powerful-flame-cyberweapon-tied-to-powerfully-angry-birds/
Varför är malware och bedräger spridda via dåligt skrivna mail med tydliga röda flaggor?

Why do Nigerian Scammers Say They are from Nigeria? http://research.microsoft.com/pubs/167719/whyfromnigeria.pdf
Mord och bomber vid sidan av Malware

Iran hänger mossad agent http://www.independent.co.uk/news/world/middle-east/iran-hangs-mossad-spy-majid-jamali-fashi-for-killing-scientist-7754332.html
Vem dödar iranska kärnkraftsforskare? http://edition.cnn.com/2012/01/11/world/meast/iran-who-kills-scientists/
Massoud Ali Mohammadi http://original.antiwar.com/justin/2010/01/14/who-killed-massoud-ali-mohammadi/
Majid Shahriari & Fereydoon Abbasi Davani http://www.theguardian.com/world/2010/dec/05/iran-nuclear-experts-killings
Dariush Rezaei-Nejad http://www.pbs.org/wgbh/pages/frontline/tehranbureau/2011/07/iranian-scientist-assassinated-in-tehran-nature-of-his-work-unclear.html
Mostafa Ahmadi-Roshan http://www.theguardian.com/world/2012/jan/11/iran-nuclear-scientist-killed
