### ISSUE TITLE
Kan ni inte prata om vad man kan förvänta sig när man rapporterar ett säkerhetshål hos företag ang: Respons? Belöning?

### ISSUE THREAD

**Issue by mjidhage** [mjidhage/sakerhetspodcasten#32]
Niclas Nilsson @nilssonniclas

**Comment by mjidhage** [comment]
Rickard Andersson @rickard2: gärna om open source också. Har själv rättat buggar men ej fått cred, borde man inte få det tycker ni?

**Comment by blaufish** [comment]
Besvarad i nästa podcast
