### ISSUE TITLE
Intervju med Dr Ulf Larson

### ISSUE THREAD

**Issue by mjidhage** [mjidhage/sakerhetspodcasten#4]
Telekomsäkerhet. Jag skulle specifikt vilja prata om hur de jobbar med SDLC och säkerhetstestning när det bygger telekom-stuffs. En komponent i telekomvärlden ligger lite mellan embedded och linux-världen, typ. Därav att den är intressant även utanför telekom-sfären

**Comment by blaufish** [comment]
flyttad till backlogg och stängd
