### ISSUE TITLE
Shownotes Säkerhetspodcasten avs.32 – Ostrukturerat V.37

### ISSUE THREAD

**Issue by mjidhage** [mjidhage/sakerhetspodcasten#42]
Delvis inlagda, klart?

**Comment by blaufish** [comment]
Lyssna

iTunes | mp3

Innehåll

Detta är det trettioandra avsnittet av Säkerhetspodcasten, i vilken panelen diskuterar den senaste tidens nyheter. Bland annat: E-Val, The Fappening, SCADA-malware, stulna Gmail-konton och mycket mer!

Panelen har dessutom precis valt ut två lyssnare som får de biljetter SEC-T har gett oss. Tre personer fick lika många röster, och genom lottning blev följande två slutgiltliga vinnare:

@ClaesWallin: @sakpodcasten 3e året av kärvt & fattigt studenliv på HH, en dyr sambo, har tömt kassan! Chansen att lära på Sec-T hade varit asgrymt!
@Scopat:  jag behöver gå på sec-t så jag kan lära mig att säkra mitt iCloud! Jag vill inte att mina nakenbilder ska spridas! :p
Inspelat: 2014-09-11. Längd: 1:05:50.

Länkar

Svensk artikel kritisk till e-val: SvD Allvarliga brister i dagens e-röstning
Dokumentär om brister i trovärdigheten i amerikanska e-val: Hacking Democracy
Schneier: The Problem with Electronic Voting Machines
SvD 2010: Försökte hacka valet med röstsedlar
The Fappening / iCloud: Apple Media Advisory. "certain celebrity accounts were compromised by a very targeted attack on user names, passwords and security questions"
iBrute https://github.com/hackappcom/ibrute
InfoSec Taylor Swift twitter: @SwiftOnSecurity  tumbler: swiftOnSecurity
Dropbox vidöppen 2011
SCADA-Mallware \ Dragon Fly Symantecs Whitepaper F-Secure´s breakdown
Flashback diskuterar att Researchgruppen påstår sig ha dump av Flashback användardatabasen
Linkedin breach http://en.wikipedia.org/wiki/2012_LinkedIn_hack
Gawker UTF-8 buggen
UTF-8 Replacement Character (tecknet alla specialtecken kan konverteras till om man fuck'at upp sin lösenordsinmatningsdialog, relativt vanligt fel!)
Tor-hacket 2007: Tor möjliggjorde ambassadhack
FBI skall börja banda förhör / erkännanden: DOJ reverses no-recording policy for interrogations
Satoshi Nakamoto gmx hack
Chrome sunsetting SHA-1
Chrome Public Key Pinning
Mozilla Public Key Pinning
Wifi: Client Isolation
Arris backdoor
Comodo Reverse Engineering: "Don't worry Comodo, I'm not a plagiarist, I'm just looking for vulnerabilities. Peace."
‘Sorry about the bomb’: Aussie police apologize for 'training device' left in Sydney airport
