### ISSUE TITLE
Shownotes Säkerhetspodcasten avs.30 – Q & A

### ISSUE THREAD

**Issue by mjidhage** [mjidhage/sakerhetspodcasten#45]

**Comment by blaufish** [comment]
Lyssna

iTunes | mp3

Innehåll

Detta är det trettionde avsnittet av Säkerhetspodcasten, i vilket panelen svarar på frågor från er lyssnare! Vi pratar Diginotar, Bug Bounties, David Guettas USB-minne, LibreSSL och mycket mer.

Säkerhetskonferenser i sverige: SEC-T, OWASP (chapters: Sverige, Stockholm, Göteborg, ...), Next Generation Threats, Internet Dagarna, Internet Security Expo, ISACA, ASIS, FOSS

Inspelat: 2014-06-12. Längd: 1:18:28.

Länkar

MP3 Bitrates http://computer.howstuffworks.com/mp32.htm http://blog.signalleaf.com/blog/2013/12/18/mp3-bit-rates/
Diginotar http://www.scmagazineuk.com/diginotar-hack-details-revealed-by-dutch-government/article/266739/
Diginotar Foxit slutgiltliga Black Tulip rapport, 100 sidor: http://www.rijksoverheid.nl/documenten-en-publicaties/rapporten/2012/08/13/black-tulip-update.html http://www.rijksoverheid.nl/bestanden/documenten-en-publicaties/rapporten/2012/08/13/black-tulip-update/black-tulip-update.pdf
Encase Enterprise
Access data e-discovery
OCSP världens svåraste förkortning? http://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol
ChangeCipherSpec sårbarheten
Coq theorem grunkan
Falsk nyhet: David Guetta tappat bort sin usb-sticka
Linux Foundation Core Infrastructure Initive
libressl more than 30 days later
origins of libressl: "It was clear that a fork was the only solution and that working with upstream would be a futile effort."
Gamla twitterkontot @OpenSSLFact
Hur target missade hacket trotts varningar http://www.businessweek.com/articles/2014-03-13/target-missed-alarms-in-epic-hack-of-credit-card-data
Bug Bounty program https://bugcrowd.com/list-of-bug-bounty-programs
Katie Moussouris tidigiare Microsoft Security numera Hackerone
Katies ISO-standarder: vulnerability disclosure (29147), secure development (27034), penetration testing (20004-2) and Vulnerability Handling Processes (30111)
