### ISSUE TITLE
Shownotes Säkerhetspodcasten avs.29 – Sommaravsnitt 2014

### ISSUE THREAD

**Issue by mjidhage** [mjidhage/sakerhetspodcasten#46]

**Comment by blaufish** [comment]
TrueCrypt lägger ner http://truecrypt.sourceforge.net/
Mer 0m Trucrypt: http://nakedsecurity.sophos.com/2014/06/20/truecrypt-mystery-forking-weirder-than-before/
NoIP Details on Microsoft Takeover
Kapersky Gone fubar: Microsoft nukes No-IP, gets fallout "These include (and not limited to): Flame/Miniflame, ..."
Blackwater påstås ha hotat USAs inspektörer i Irak http://www.nytimes.com/2014/06/30/us/before-shooting-in-iraq-warning-on-blackwater.html
