### ISSUE TITLE
Shownotes Säkerhetspodcasten avs.22 – Verktyg

### ISSUE THREAD

**Issue by mjidhage** [mjidhage/sakerhetspodcasten#50]

**Comment by blaufish** [comment]
Lyssna

iTunes | mp3

Innehåll

Detta är det tjugoandra ordinarie avsnittet av Säkerhetspodcasten, i vilket panelen diskuterar the tools of the trade, med andra ord vilka verktyg som man med fördel använder i det dagliga säkerhetsarbetet.

Inspelat: 2014-03-13. Längd: 1:07:20.

Länkar

Zone Transfer
nmap
nmap scripts
TOR
nessus
nexpose
netcat 
tcpdump wireshark tshark
wireshark för usb
nipper studio
google avancerad sökning (se även google dorks)
burp suite
zap proxy
IBM Rational App Scan
dex2jar
ollydbg
ida pro
brainfuck
forensics case notes
maltego (video om den)
metasploit
