### ISSUE TITLE
Intervju IT-rätt

### ISSUE THREAD

**Issue by mjidhage** [mjidhage/sakerhetspodcasten#52]
Agnes Andersson Hammarstrand har vi intervju med. Ett annat namn vi fått via kommentarer på siten är 
"Gällande IT-rätt.

Skicka iväg ett mail till los@kth.se
Jag vet att han håller distanskurser i IT-Säkerhet samt föreläser för juridikstudenterna vid UU. Han kam nog tipsa om något.

F.ö är hans distanskurser inom IT-Säk väldigt informativa.

Hi117V
Hi119V
Sedan kommer jag inte på 3an"

**Comment by blaufish** [comment]
@mjidhage ordnung musst sein. är det 2 ärenden på samma lapp? splitta isf. Skriv om så det blir begripligt.

**Comment by blaufish** [comment]
Agnes Andersson Hammarstrand intervjun räknar jag som försvunnen eftersom den är gammal och den inte finns där vi förvarar klart material @rbodforss . Jag stänger detta ärende. Mattias får skriva en  ny lapp som är tydlig om vi skall göra något.
