### ISSUE TITLE
Historiska Malware

### ISSUE THREAD

**Issue by mjidhage** [mjidhage/sakerhetspodcasten#62]
Melissa, ILoveYou etc
Önskan från @Blankforte

**Comment by mjidhage** [comment]
Kört en första vända. Har dock inte tittat på alla och inte ngt alls på makron

**Comment by blaufish** [comment]
Jag har länkar till nästan alla i whiteboard Google doc filen :-)

**Comment by blaufish** [comment]
Säkerhetspodcasten avs.36 – Historiska malware AV Admin DEN 8 DECEMBER 2014 I SÄKERHETSPODS
Lyssna

iTunes | mp3

Innehåll

I detta avsnitt av Säkerhetspodcasten diskuterar panelen olika historiska malware. Vi kör i kronologisk ordning och går igenom några av de största, läskigaste och roligaste fulkoderna som florerat genom tiderna. Bland annat Brain, ILoveYou, Slammer, SAMY Worm och många fler…

Inspelat: 2014-11-13. Längd: 1:36:20.

Länkar

Tipstack till: @Blankforte Kristoffer Eriksson
1986 Brain http://virus.wikidot.com/brain
1988 Morris http://virus.wikidot.com/morris
1990 form http://virus.wikidot.com/form
1994 junkie http://virus.wikidot.com/junkie
1998 CIH http://virus.wikidot.com/cih
2000 I love you http://en.wikipedia.org/wiki/ILOVEYOU http://virus.wikidot.com/loveletter
2001 Code Red http://en.wikipedia.org/wiki/Code_Red_(computer_worm)
2003 Blaster http://en.wikipedia.org/wiki/Blaster_(computer_worm)
2006 Samy http://en.wikipedia.org/wiki/Samy_(computer_worm) http://virus.wikidot.com/spacehero
Andra listor på kända malware:

http://antivirus.about.com/od/whatisavirus/a/A-Brief-History-Of-Malware-The-First-25-Years.htm
http://arxiv.org/pdf/1302.5392.pdf
http://en.m.wikipedia.org/wiki/List_of_computer_viruses
