### ISSUE TITLE
Trasiga bildlänkar på avatarer på sakerhetspodcasten.se

### ISSUE THREAD

**Issue by mjidhage** [mjidhage/sakerhetspodcasten#65]

**Comment by mjidhage** [comment]
Jag har dessvärre tagit bort felet genom att ange ny default-avatar till en bild som funkar. Vi behöver bestämma hur default besöksavataren skall se ut och uppdatera när vi har lagat issuen med trasiga bildlänkar i mediabiblioteket

**Comment by blaufish** [comment]
Mattias har löst felet
