### ISSUE TITLE
Trasiga bildlänkar under media på sakerhetspodcasten.se

### ISSUE THREAD

**Issue by mjidhage** [mjidhage/sakerhetspodcasten#66]
ser ut som att det primärt är mixminus-bilderna som fallit bort. Har vi gjort ngt med siten? Packat ihop och flyttat den eller nåt?

**Comment by mjidhage** [comment]
Hmm, jag noterar att om man laddar upp nya bilder så hittar inte siten dem, broken image link: http://sakerhetspodcasten.se/wp-content/uploads/2015/02/Emotions_icon_logos3.png

**Comment by mjidhage** [comment]
Full disk? Fel läs/skriv-rättigheter?

**Comment by blaufish** [comment]
@mjidhage @JohanRM ni får besluta om det skall felsökas. Stänger (backlog) tills vidare.
