### ISSUE TITLE
klippa: sec-t tema avsnitt

### ISSUE THREAD

**Issue by blaufish** [mjidhage/sakerhetspodcasten#79]

**Comment by blaufish** [comment]
@mjidhage yo gör klart eller dumpa över på mig

**Comment by blaufish** [comment]
@mjidhage 60+ dagar för att klippa ett avsnitt dafuq?

**Comment by mjidhage** [comment]
Sparka inte på folk som ligger ned. Vi spelade in den på den bärbara riggen har jag för mig? Det förklarar varför jag inte hittar filen hemma. Den ligger på jobbdatorn. Dubbelkollar imorgon.
