### ISSUE TITLE
VPN - Krypteringstjänster (tinkerbeard@tuta.io)

### ISSUE THREAD

**Issue by mjidhage** [mjidhage/sakerhetspodcasten#86]
Hej Säkerhetspodcasten!

Tack för att jag på något underligt sätt hittade er i den yttre rymden och vilken kvalité och standard ni håller! Gillar även att ni sätter ton på humorn i alla era avsnitt.

Jag har enbart lyssnat på dom senaste avsnitten och vet inte ifall ni tar upp ämnet kring VPN tjänster men det vore intressant av er att forska i ämnet. Vilken ska man använda? Vad ska man tänka på när man väljer en tjänst? Hur används en VPN? Finns det några bakdörrar? Finns det några risker vid användandet? Varför ska en vanlig Svensson använda en VPN? Osv.

Jag själv har starka mål till varför jag använder VPN men vill gärna höra er diskussioner kring ämnet. Ev. Om ni använder det själv och i så fall vilken? Använder ni på både på dator och i/eller mobil?

Mvh

**Comment by blaufish** [comment]
besvarad
