### ISSUE TITLE
VPN (love@lovebart.se Love Björk)

### ISSUE THREAD

**Issue by mjidhage** [mjidhage/sakerhetspodcasten#87]
Hej!

Tack för en trevlig podcast (även om den kommer ut allt för sällan ;) )! I ert senaste avsnitt (49) pratar ni om att använda säkra och bra VPN:er. Det kan dock vara extremt svårt att veta vilka företag som går att lita på och vilka som snällt delar med sig av data när NSA knackar på dörren. Därför tycker jag att ni i kommande avsnitt ska prata om just detta. Vad använder ni själva för VPN-tjänster? Varför litar ni på dem? Ungefär hur mycket är rimligt att betala för en VPN per månad? Kanske en jämförelse av kostnad/säkerhet/hastighet (datatakt och delay).

Ni har i något avsnitt också talat om lagring. Det är ett mycket intressant ämne som ofta leder till debatt i säkerhetsvärlden. Ska vi lita på molnlagring? Bör vi istället ha en server hemma? Isåfall hur ska denna kommas åt? Räcker det med FTP eller bör SFTP istället användas? Finns det något ännu bättre sätt? VPN:a hem och sen köra SMB som är låst mot det lokala nätet? Hur avväger vi säkerhet mot smidighet vad det gäller privata filer? Hur gör ni?

Hoppas detta hjälper er och leder till någon form av diskussion mellan er i något kommande avsnitt! (Och tack för all trevlig lyssning)!

Allt gott,

Love Björk

**Comment by blaufish** [comment]
besvarad
