### ISSUE TITLE
fixa släppkalendern

### ISSUE THREAD

**Issue by blaufish** [mjidhage/sakerhetspodcasten#90]
@mjidhage kalenderbokning skall uppdateras enligt klubbat förslag!
Exempel februari: 
- spelar vi in torsdag 11 feburari 
- så kommer första släpp på måndag 15 februari (+ 4 dagar)
- nästa släpp 29 februari (+ 28 dagar)

så schemat är T, T+4, T+28, där T är inspelning och det andra är släpp.

Klart som korvspad!

**Comment by mjidhage** [comment]
Eller så kör vi T, T+4, T+18 så blir det varannan vecka...
